spring:
  application:
    name: store

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: yuri
    password: senha123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # SQL formatado
    hibernate:
      ddl-auto: update     # ou create, create-drop, validate — escolha o que deseja

logging:
  level:
    org.hibernate.SQL: DEBUG          # mostra as queries
    org.hibernate.orm.jdbc.bind: TRACE  # mostra os parâmetros das queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # valores bindados

server:
  port: 8081

